import { useState, useMemo, useRef, type FormEvent, type ChangeEvent } from 'react'
import { Icon } from '../components/Icon'
import { Dialog } from '../components/Dialog'
import { formatSize } from '../components/StatusBadge'
import { UserText } from '../components/UserText'

export interface ManualTemplate {
  id: string
  title: string
  format: 'WORD' | 'EXCEL' | 'PDF'
  fileName: string
  fileSize: number
  description: string
  updatedAt: string
}

const STORAGE_KEY = 'manual_management_templates_v1'

function loadSavedTemplates(): ManualTemplate[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) {
      return JSON.parse(raw)
    }
  } catch {
    // fallback
  }
  return []
}

function saveTemplates(items: ManualTemplate[]) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items))
  } catch {
    // ignore
  }
}

export function TemplatesPage() {
  const [templates, setTemplates] = useState<ManualTemplate[]>(loadSavedTemplates)
  const [search, setSearch] = useState('')
  const [uploading, setUploading] = useState(false)
  const [notice, setNotice] = useState('')
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const visible = useMemo(() => {
    const term = search.trim().toLowerCase()
    if (!term) return templates
    return templates.filter(t =>
      t.title.toLowerCase().includes(term) ||
      t.description.toLowerCase().includes(term) ||
      t.fileName.toLowerCase().includes(term)
    )
  }, [templates, search])

  function handleFileChange(e: ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0] || null
    setSelectedFile(file)
  }

  function handleUpload(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const form = event.currentTarget
    const data = new FormData(form)
    const fileInput = form.elements.namedItem('file') as HTMLInputElement | null
    const file = selectedFile || fileInput?.files?.[0] || (data.get('file') as File | null)
    const title = String(data.get('title') || '').trim()
    const description = String(data.get('description') || '').trim()

    if (!title) return
    const fileName = file?.name || 'template_document.docx'
    const fileSize = file?.size || 1024

    const ext = fileName.slice(fileName.lastIndexOf('.')).toLowerCase()
    const format: 'WORD' | 'EXCEL' | 'PDF' =
      ext === '.xlsx' || ext === '.xls'
        ? 'EXCEL'
        : ext === '.pdf'
        ? 'PDF'
        : 'WORD'

    const newTemplate: ManualTemplate = {
      id: `tpl-${Date.now()}`,
      title,
      format,
      fileName,
      fileSize,
      description: description || 'Custom user uploaded template.',
      updatedAt: new Date().toISOString(),
    }

    setTemplates(prev => {
      const updated = [newTemplate, ...prev]
      saveTemplates(updated)
      return updated
    })
    setUploading(false)
    setSelectedFile(null)
    setNotice(`Template "${title}" uploaded successfully.`)
  }

  function handleDelete(id: string, title: string) {
    if (!window.confirm(`Delete template "${title}"?`)) return
    setTemplates(prev => {
      const updated = prev.filter(t => t.id !== id)
      saveTemplates(updated)
      return updated
    })
    setNotice(`Template "${title}" removed.`)
  }

  function handleDownload(tpl: ManualTemplate) {
    const sampleContent = `Document Template: ${tpl.title}\nFile: ${tpl.fileName}\nGenerated by Manual Management System`
    const blob = new Blob([sampleContent], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = tpl.fileName
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <>
      <div className="page-heading">
        <div>
          <h1>Manual Templates</h1>
          <p>Document templates and starters for creating standardized manuals and procedures.</p>
        </div>
        <button className="btn-primary" onClick={() => { setSelectedFile(null); setUploading(true) }}>
          <Icon name="plus" size={18} />
          Upload Template
        </button>
      </div>

      {notice && (
        <p role="status" className="mb-5 flex items-center justify-between rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">
          <span>{notice}</span>
          <button type="button" aria-label="Dismiss notification" className="h-8 w-8 text-emerald-700 hover:text-emerald-900" onClick={() => setNotice('')}>
            &times;
          </button>
        </p>
      )}

      {/* Search Bar */}
      {templates.length > 0 && (
        <div className="panel project-filters mb-6">
          <label className="field flex-1">
            Search Templates
            <input
              type="search"
              placeholder="Search by template title, filename, or description..."
              value={search}
              onChange={e => setSearch(e.target.value)}
            />
          </label>
        </div>
      )}

      {/* Templates Grid */}
      {visible.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {visible.map(tpl => (
            <article key={tpl.id} className="project-card flex flex-col justify-between">
              <div>
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-2">
                      <span className={`inline-flex items-center rounded-md px-2 py-0.5 text-xs font-semibold ${
                        tpl.format === 'WORD'
                          ? 'bg-blue-100 text-blue-900 border border-blue-200'
                          : tpl.format === 'EXCEL'
                          ? 'bg-emerald-100 text-emerald-900 border border-emerald-200'
                          : 'bg-rose-100 text-rose-900 border border-rose-200'
                      }`}>
                        {tpl.format}
                      </span>
                    </div>
                    <h2 className="text-lg font-semibold text-slate-900 break-words">{tpl.title}</h2>
                  </div>
                  <button
                    type="button"
                    aria-label={`Delete template ${tpl.title}`}
                    className="text-slate-400 hover:text-red-600 p-1 transition-colors"
                    onClick={() => handleDelete(tpl.id, tpl.title)}
                  >
                    <Icon name="trash" size={16} />
                  </button>
                </div>

                <UserText as="p" className="mt-3 text-sm text-slate-600 leading-relaxed break-words" text={tpl.description}>
                  {tpl.description}
                </UserText>
              </div>

              <div className="mt-5 pt-4 border-t border-slate-100">
                <div className="flex items-center justify-between text-xs text-slate-500 mb-3">
                  <span className="truncate max-w-[180px] font-mono">{tpl.fileName}</span>
                  <span>{formatSize(tpl.fileSize)}</span>
                </div>
                <button
                  className="btn-secondary w-full"
                  aria-label={`Download template ${tpl.title}`}
                  onClick={() => handleDownload(tpl)}
                >
                  <Icon name="arrow" size={16} style={{ transform: 'rotate(90deg)' }} />
                  <span>Download Template</span>
                </button>
              </div>
            </article>
          ))}
        </div>
      )}

      {/* Empty State */}
      {templates.length === 0 && (
        <div className="panel empty-state py-12 text-center">
          <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 text-slate-500">
            <Icon name="template" size={28} />
          </div>
          <h2 className="text-xl font-bold text-slate-900">No Templates Yet</h2>
          <p className="mt-1 text-sm text-slate-600 max-w-md mx-auto">
            Upload standard template files (.docx, .xlsx, .pdf) for your team to use as starters when authoring manuals.
          </p>
          <button className="btn-primary mt-6" onClick={() => { setSelectedFile(null); setUploading(true) }}>
            <Icon name="plus" size={18} />
            Upload First Template
          </button>
        </div>
      )}

      {templates.length > 0 && visible.length === 0 && (
        <div className="panel empty-state py-8 text-center">
          <h2>No matching templates</h2>
          <p>No templates matched your search term "{search}".</p>
          <button className="btn-secondary mt-4" onClick={() => setSearch('')}>
            Clear Search
          </button>
        </div>
      )}

      {/* Upload Template Modal */}
      {uploading && (
        <Dialog title="Upload Manual Template" onClose={() => setUploading(false)}>
          <form onSubmit={handleUpload}>
            <fieldset className="space-y-4 px-6 py-5">
              <label className="field">
                Template Title *
                <input name="title" required placeholder="e.g. Standard Operating Procedure Template" autoFocus />
              </label>
              <label className="field">
                Description
                <textarea name="description" rows={3} placeholder="Describe what this template is for and when team members should use it..." />
              </label>

              {/* Styled File Upload Dropzone */}
              <div>
                <span className="mb-1 block text-sm font-medium text-slate-700">Select Template File (.docx, .xlsx, .pdf) *</span>
                <input
                  ref={fileInputRef}
                  type="file"
                  name="file"
                  id="template-file-input"
                  aria-label="Select Template File"
                  required
                  accept=".docx,.doc,.xlsx,.xls,.pdf"
                  className="sr-only"
                  onChange={handleFileChange}
                />

                {!selectedFile ? (
                  <div
                    onClick={() => fileInputRef.current?.click()}
                    onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); fileInputRef.current?.click() } }}
                    tabIndex={0}
                    role="button"
                    aria-label="Choose file to upload"
                    className="flex flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-300 bg-slate-50/70 p-6 text-center transition-colors hover:border-blue-600 hover:bg-blue-50/50 cursor-pointer focus:border-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                  >
                    <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white shadow-sm border border-slate-200 text-blue-900">
                      <Icon name="upload" size={20} />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-slate-800">
                        Click to select a file <span className="font-normal text-slate-500">or drag and drop</span>
                      </p>
                      <p className="mt-0.5 text-xs text-slate-500">
                        Supports Word (.docx), Excel (.xlsx), or PDF (up to 50MB)
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="flex items-center justify-between rounded-xl border border-blue-200 bg-blue-50/60 p-4">
                    <div className="flex items-center gap-3 min-w-0">
                      <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-blue-900 text-white">
                        <Icon name="file" size={20} />
                      </div>
                      <div className="min-w-0">
                        <p className="truncate text-sm font-semibold text-slate-900">{selectedFile.name}</p>
                        <p className="text-xs text-slate-500">{formatSize(selectedFile.size)}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <button
                        type="button"
                        className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50"
                        onClick={() => fileInputRef.current?.click()}
                      >
                        Change
                      </button>
                      <button
                        type="button"
                        className="rounded-lg p-1.5 text-slate-400 hover:text-red-600"
                        aria-label="Remove selected file"
                        onClick={() => {
                          setSelectedFile(null)
                          if (fileInputRef.current) fileInputRef.current.value = ''
                        }}
                      >
                        <Icon name="close" size={16} />
                      </button>
                    </div>
                  </div>
                )}
              </div>
            </fieldset>

            <div className="modal-footer">
              <button type="button" className="btn-secondary" onClick={() => { setSelectedFile(null); setUploading(false) }}>
                Cancel
              </button>
              <button type="submit" className="btn-primary">
                Upload Template
              </button>
            </div>
          </form>
        </Dialog>
      )}
    </>
  )
}
